apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
     name: aks-internal-ingress-controller-tls-secret-csi-akv
     namespace: rii-services
spec:
     provider: azure
     parameters:
       usePodIdentity: "true"
       keyvaultName: "${KEYVAULT_NAME}"
       objects:  |
         array:
           - |
             objectName: aks-internal-ingress-controller-tls
             objectAlias: tls.crt
             objectType: cert
           - |
             objectName: aks-internal-ingress-controller-tls
             objectAlias: tls.key
             objectType: secret
       tenantId: "${TENANT_ID}" 