apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: rii-services
  labels:
    app: backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 3002
  type: ClusterIP
